### ISSUE TITLE
Ревизия условий формирования bst из dtx

### ISSUE THREAD

**Issue by LSinev** [kia999/GOST#10]
Странные условия, может лишние, может не работают и следует удалить:
https://github.com/kia999/GOST/blob/develop/source/bibtex/gost/gost.dtx#L5361
https://github.com/kia999/GOST/blob/develop/source/bibtex/gost/gost.dtx#L5385

Это вообще отключено, похоже: https://github.com/kia999/GOST/blob/develop/source/bibtex/gost/gost.dtx#L5241

**Comment by kia999** [comment]
Solved
