### ISSUE TITLE
Положение буквы "c." после количества страниц для книг

### ISSUE THREAD

**Issue by ghost** [kia999/GOST#18]
По ГОСТу для книг строчная буква "с." должна идти после количества страниц, а получается до, к тому же, прописная.
Например: "...Химия, 1998. – С. 241", а должно быть  – "...Химия, 1998. – 241 с."
Так же и для англоязычных записей:
"...Academic Press, 2008. – P. 382." – "...Academic Press, 2008. – 382 p."

**Comment by LSinev** [comment]
При обработке какого bib-файла вы это получили (интересует содержимое конкретных bib-записей, где бы указанный недочёт воспроизводился)?

**Comment by ghost** [comment]
Вот этот файл:
`@BOOK{radion2010,
  title={Физико-химические методы анализа. Лабораторный практикум},
  author={Радион, Е. В. and Соколовский, А. Е. and Коваленко, Н. А. and Супиченко, Г. Н. and Кийко, Т. Н.},
  pages={108},
  year = {2010},
  publisher={Минск : БГТУ},
  language={russian}
}
@BOOK{fanali2013,
author = {Fanali, S. and Haddad, P. R. and Poole, C. F. and Schoenmakers, P. and Lloyd, D.},
year = {2013},
month = {01},
pages = {520},
publisher = {Elsevier},
title = {Liquid Chromatography: Fundamentals and Instrumentation}
}
@article{Zhu2017,
  doi = {10.4172/2157-7064.1000358},
  url = {https://doi.org/10.4172/2157-7064.1000358},
  year  = {2017},
  publisher = {{OMICS} Publishing Group},
  volume = {08},
  number = {02},
  author = {Bo, Zhu and Ying, Y.  Chen},
  title = {Development and Application of Liquid Chromatography in Life Sciences},
  journal = {Journal of Chromatography {\&} Separation Techniques},
  language = {english}
}

@BOOK{Snyder2009,
  doi = {10.1002/9780470508183},
  year  = {2009},
  month = {nov},
  publisher = {John Wiley {\&} Sons,  Inc.},
  author = {Snyder, L. R. and Kirkland, J. J. and Dolan, J.W.},
  title = {Introduction to Modern Liquid Chromatography}
}

@BOOK{Ehler1993,
  title={Яды в нашей пище},
  author={Эхлер, В.},
  pages={188},
  year={1993},
  publisher={М : Мир},
  language={russian}
}

@article{Rekhi2017,
  doi = {10.1080/10408347.2017.1343659},
  year  = {2017},
  month = {jun},
  publisher = {Informa {UK} Limited},
  volume = {47},
  number = {6},
  pages = {524--537},
  author = {Rekhi, H. and Rani, S. and Sharma, N. and Malik, A. K.},
  title = {A Review on Recent Applications of High-Performance Liquid Chromatography in Metal Determination and Speciation Analysis},
  journal = {Critical Reviews in Analytical Chemistry}
}

@inbook{Meyer2014,
author = {Meyer, V. R.},
publisher = {American Cancer Society},
isbn = {9780470027318},
title = {High Pressure Liquid Chromatography and Ultra?high Pressure Liquid Chromatography of Plants: Basic Concepts},
booktitle = {Encyclopedia of Analytical Chemistry},
chapter = {},
pages = {1-20},
doi = {10.1002/9780470027318.a9908},
eprint = {https://onlinelibrary.wiley.com/doi/pdf/10.1002/9780470027318.a9908},
year = {2014},
keywords = {HPLC, UHPLC, high?performance liquid chromatography, ultra high?performance liquid chromatography, theory of HPLC, plant analysis},
abstract = {Abstract High?performance liquid chromatography (HPLC) is an essential method in plant analysis. Although it is primarily a separation method, it offers also the possibility of on?line quantitative analysis during the separation. It can be used for both, the investigation of classes of compounds as well as of individual substances. HPLC is an instrumental method of great flexibility with regard to the separation conditions and to the detection principle. In any case, high pressure is needed; conventional HPLC acts up to about 350?bar. As the available pressure limits the speed of analysis and its separation power, the more recent technology of ultra high?performance liquid chromatography (UHPLC) works at pressures up to 1000?bar. It allows very fast analyses or high peak capacity (i.e., the number of resolved compounds) or a combination of both demands. The separation environment can be aqueous, for example, in reversed?phase or ion?exchange HPLC, or nonpolar with organic solvents in adsorption chromatography, thus allowing a great choice of investigative principles.}
}

@BOOK{HAGEL2008xv,
title = {Handbook of Process Chromatography (Second Edition)},
editor = {Lars Hagel and G?nter Jagschies and Gail Sofer},
publisher = {Academic Press},
edition = {Second Edition},
address = {Amsterdam},
pages = {382},
year = {2008},
isbn = {978-0-12-374023-6},
doi = {https://doi.org/10.1016/B978-012374023-6.50001-4},
author = {Hagel, H. and Jagschies, G. and Sofer, G.}
}

@article{jaimez2000application,
  title={Application of the assay of aflatoxins by liquid chromatography with fluorescence detection in food analysis},
  author={Jaimez, J. and Fente, C. A. and Vazquez, B. I. and Franco, C. M. and Cepeda, A. and Mahuzier, G. and Prognon, P.},
  journal={Journal of Chromatography A},
  volume={882},
  number={1-2},
  pages={1--10},
  year={2000},
  publisher={Elsevier}
}

@BOOK{Nikalje2017,
author = {Nikalje, A.},
year = {2017},
month = {03},
pages = {284},
title = {A Handbook of Chromatography},
isbn = {978-3-330-65032-9}
}

@BOOK{pozd2002,
  title={Гигиенические основы питания, безопасность и экспертиза пищевых продуктов},
  author={Позняковский, В. М.},
  year={2002},
  pages={455},
  publisher={Сиб. унив. изд-во Новосибирск},
  language={russian}
}

@BOOK{Petruhin2006,
  title={Аналитическая химия. Химические методы анализа},
  author={Петрухин, О. М.},
  year={2006},
  pages={397},
  publisher={М. : Путь, Альянс},
  language={russian}
}

@article{monisov1994,
  title={Проблемы безопасности пищевых продуктов в России},
  author={Монисов, А. А. and Тутельян, В. А. and Хотимченко, С. А. and Терешкова, Л. П.},
  journal={Вопросы питания},
  volume={3},
  pages={33-39},
  year={1994},
  language={russian}
}

@BOOK{Koreshkov1965,
  title={Основы аналитической химии},
  author={Крешков, А. П.},
  year={1970},
  pages={472},
  publisher={М. : Химия},
  language="russian"
}

@BOOK{Kirher1981,
  title={Тонкослойная хроматография},
  author={Кирхер, Ю.},
  year={1981},
  publisher={М. : Мир},
  pages={616},
  langid={russian}
}
@article{davankov2003,
  title={Сто лет хроматографии},
  author={Даванков, В. А. and Яшин, Я. И.},
  journal={Вестник российской академии наук},
  volume={73},
  number={7},
  pages={637--646},
  year={2003},
  publisher={Федеральное государственное унитарное предприятие Академический научно-издательский, производственно-полиграфический и книгораспространительский центр Наука},
  language={russian}
}

@BOOK{Tiunov1994,
  title={Вредные химические вещества : Галоген- и кислородсодержащие орган. соединения : Справочник},
  author={Бандман, А. Л. },
  editor={Филова, В. А. and Тиунова, Л. А.},
  publisher={СПб. : Химия},
  pages={686},
  year={1994},
  language={russian}
}

@BOOK{vasiliev1989,
  title={Аналитическая химия: учебник для студентов химико-технологических специальностей вузов: в 2ч. Ч. 2.},
  author={Васильев, В. П.},
  journal={М.: Высшая школа},
  year={1989},
  language={russian}
}

@BOOK{sinitsin1988,
  title={Высокоэффективная жидкостная хроматография в биохимии},
  author={Синицын, А. П. and Хеншен, А. and Березин, И. В.},
  year={1988},
  pages={688},
  address = {Москва},
  publisher={Мир},
  language={russian}
}

@BOOK{Perelygin2010,
  title={Лабораторный практикум по дисциплине <<Безопасность товаров>>},
  author={Перелыгин, Н. О. and Елисеева, Л. Г. and Положишникова, М. А.},
  year={2010},
  publisher={М.: Изд-во Российский экономический университет им. Г.В. Плеханова},
  pages={52},
  language={russian}
}

@BOOK{Pilipenko1998,
  title={Аналитическая химия : в 2 Т.},
  author={Пилипенко, А. Т. and Пятницкий, И. В.},
  year={1998},
  publisher={М.: Химия},
  pages={241},
  language={russian}
}

@BOOK{citovich2004,
  title={Курс аналитической химии},
  author={Цитович, И. К.},
  year={2004},
  publisher={М.: Лань},
  pages={496},
  language={russian}
}
@BOOK{aivazov1983,
  title={Введение в хроматографию},
  author={Айвазов, Б. В.},
  year={1983},
  pages={240},
  publisher={Высш. шк.},
  language={russian}
}

@article{amelin2013,
  title={Хроматографические методы определения микотоксинов в пищевых продуктах},
  author={Амелин, В. Г. and Карасева, Н. М. and Третьяков, А. В.},
  journal={Журнал аналитической химии},
  volume={68},
  number={3},
  pages={212--223},
  year={2013},
  publisher={Федеральное государственное унитарное предприятие Академический научно-издательский, производственно-полиграфический и книгораспространительский центр Наука},
  language={russian}
}

@BOOK{engelgard1980,
  title={Жидкостная хроматография при высоких давлениях},
  author={Энгельгардт, Х.},
  publisher={МИР},
  year={1980},
  page={250}
}`

**Comment by kia999** [comment]
Коллеги!

Пакет гост делает всё правильно. Неправильно оформлена библиографическая
запись в БД. Вместо

pages = {241}

нужно

pagetotal = {241}

-----------------------------------------
Igor A. Kotelnikov
igor.kotelnikov@gmail.com

Budker Institute of Nuclear Physics
Novosibirsk, 630090, Russia
tel: +7 383 3294268 (office)
-----------------------------------------


ср, 27 июн. 2018 г. в 18:25, RenatW <notifications@github.com>:

**Comment by ghost** [comment]
Огромное спасибо!
