### ISSUE TITLE
"\" can't start a style-file command---line 2611 of file ugost2008.bst

### ISSUE THREAD

**Issue by einhander** [kia999/GOST#23]
Добрый день, 
Перестала собираться библиография со стилем ugost2008.bst
Пример bib  файла:
````
@ARTICLE{Stamatov20062108,
  author = {Alvarez, Jon and Lopez, Gartzen and Amutio, Maider and Bilbao, Javier
	and Olazar, Martin},
  journal = {Renewable Energy},
  pages = {2108 -- 2121},
  title = {Combustion properties of slow pyrolysis bio-oil produced from indigenous
	Australian species},
  year = {2006},
  volume = {31},
  number = {13},
  keywords = {Bio-oil}
}
````
Команда запуска:
````
$ bibtex 123.aux 
This is BibTeX, Version 0.99d (TeX Live 2020/Debian)
The top-level auxiliary file: 123.aux
The style file: ugost2008.bst
Database file #1: biblio/jabref.bib
"\" can't start a style-file command---line 2611 of file ugost2008.bst
 : 
 : \endinput
(Error may have been on previous line)
(There was 1 error message)
````

Есть подозрение на свежий TexLive, так как в MikTex в виндовс такого нет.
Некоторое обсуждение есть здесь: https://www.linux.org.ru/forum/general/16335155
Там же и MWE.

**Comment by kia999** [comment]
Удалите команду \endinput из bst файлов либо обновите TeXLive, либо
возьмите пакет GOST из CTAN или из MikTeX.  \endinput \endinput\endinput
\endinput \endinput \endinputШ \endinput\endinput\endinput

Igor Kotelnikov

**Comment by einhander** [comment]
@kia999  спасибо большое!
